require.config({
    baseUrl: "/",
    // alias libraries paths
    paths: {
        'jquery': 'scripts/jquery/dist/jquery.min',
        'angular': 'scripts/angular/angular',
        'angular-ui-router': 'scripts/angular-ui-router/release/angular-ui-router.min',
        'angular-cookies': 'scripts/angular-cookies/angular-cookies',
        'async': 'scripts/requirejs/async',
        'angularAMD': 'scripts/angularAMD/angularAMD',
        'ngload': 'scripts/angularAMD/ngload',
        'toaster': 'scripts/AngularJS-Toaster/toaster',
        'xtForm': 'app/Shared/xtForm/xtForm.tpl',
        'ngDialog': 'scripts/ngDialog/js/ngDialog',
        'ui-select': 'scripts/ui-select/dist/select',
        'jquery-ui': 'scripts/jquery-ui/jquery-ui',
        'angular-ui-mask': 'scripts/angular-ui-mask/dist/mask',
        'react': 'scripts/react/react-0.14.3',
        'react-dom': 'scripts/react/react-dom.min',
        'signalR': 'scripts/signalr/jquery.signalR',
        'angular-signalr-hub': 'scripts/angular-signalr-hub/signalr-hub',
        'cw':'scripts/catiline/catiline.min',
        'perfectScrollbar': 'scripts/perfect-scrollbar/js/perfect-scrollbar',
        'perfectScrollbarJQuery': 'scripts/perfect-scrollbar/js/perfect-scrollbar.jquery',
        'ptooltip': 'app/Scheduler/ptooltip',
        'customfit': 'app/Scheduler/customfit',
        'moment': 'scripts/moment/min/moment-with-locales.min',
        'extensions': 'scripts/aextensions',
        'react-clickoutside': 'scripts/react-onclickoutside/index',
        'underscore' : 'scripts/underscore/underscore-min',
        'angular-ui-date': 'scripts/angular-ui-date/src/date',
        'angular-click-outside': 'scripts/angular-click-outside/clickoutside.directive',
      
    },
    // Add angular modules that does not support AMD out of the box, put it in a shim
    shim: {
        'angular': ['jquery'],
        'angularAMD': ['angular'],
        'angular-ui-router': ['angular'],
        'angular-cookies': ['angular'],
        'xtForm': ['angular'],
        'toaster': ['angular'],
        'ngDialog': ['angular'],
        'ui-select': ['angular'],
        'jquery-ui': ['jquery'],
        'angular-ui-mask': ['angular'],
        'signalR': ['jquery'],
        'angular-signalr-hub': ['signalR', 'angular'],
        'react-dom': ['react'],
        'customfit': ["jquery-ui"],
        'angular-ui-date': ["angular"],
        'angular-click-outside': ["angular"],
    },
    // kick start application
    deps: ['app']
});
